openapi: 3.0.0
info:
  title: API de Mascotas
  version: 1.0.0
  description: Documentación de los endpoints para gestionar mascotas.

paths:
  /api/pets:
    get:
      summary: Obtener todas las mascotas
      description: Devuelve una lista de todas las mascotas registradas en la base de datos.
      responses:
        "200":
          description: Lista de mascotas obtenida exitosamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Pet"
        "500":
          description: Error interno del servidor.

    post:
      summary: Crear una nueva mascota
      description: Registra una nueva mascota en la base de datos.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PetInput"
      responses:
        "201":
          description: Mascota creada exitosamente.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
        "400":
          description: Error en los datos enviados.
        "500":
          description: Error interno del servidor.

components:
  schemas:
    Pet:
      type: object
      properties:
        _id:
          type: string
          description: ID único generado por MongoDB.
        name:
          type: string
          description: Nombre de la mascota.
        specie:
          type: string
          description: Especie de la mascota (ej. perro, gato).
        birthDate:
          type: string
          format: date
          description: Fecha de nacimiento de la mascota.
        adopted:
          type: boolean
          description: Indica si la mascota ha sido adoptada.
        owner:
          type: string
          nullable: true
          description: ID del dueño de la mascota.
        image:
          type: string
          nullable: true
          description: URL de la imagen de la mascota.

    PetInput:
      type: object
      required:
        - name
        - specie
      properties:
        name:
          type: string
          description: Nombre de la mascota.
        specie:
          type: string
          description: Especie de la mascota.
        birthDate:
          type: string
          format: date
          description: Fecha de nacimiento de la mascota.
